### ISSUE TITLE
Set `out_xsize` = `xsize` and `out_ysize` = `ysize`

### ISSUE THREAD

**Issue by kadyb** [USDAForestService/gdalraster#26]
Could you consider setting the `out_xsize` = `xsize` and `out_ysize` = `ysize` arguments in `ds$read` as the default? Usually we want to have the same values, so the interface will be simpler.

**Comment by ctoney** [comment]
I would like to have default values for arguments in `ds$read()` and a few other places, but this is due to a limitation in `{Rcpp}` exposed classes. `GDALRaster` (along with `RunningStats` and `CmbTable`) are implemented as C++ classes, which are directly exposed in R via `RCPP_EXPOSED_CLASS`. These classes are similar in ways, but a little different from S3 and S4 classes that R users are more familiar with. `RCPP_EXPOSED_CLASS` currently does not support overloading or default values of class methods, although it does support default values for C++ stand-alone functions exposed in R (e.g., `gdalraster::create()` and `gdalraster::createCopy()`).

This is a small inconvenience for the benefits that `RCPP_EXPOSED_CLASS` provides in my opinion. Exposed classes are especially useful for the case of interfacing a library like GDAL that is itself class-based. This is how behavior we've been discussing in issue #25 is implemented. It provides a natural interface to a GDAL dataset object, which needs to be persisted in R in order to open it once and only close it later once all I/O on the dataset is completed. `{rgdal}` does this with S4 classes. `{Rcpp}` was not around Roger Bivand first wrote `{rgdal}`. Compared with the interface code that had to be written for `{rgdal}`, code for `{gdalraster}` using `{Rcpp}` exposed classes is simpler, faster to develop, more modern, and easier to maintain. For those reasons I view the issue as a small trade off.

A possible solution for `ds$read()` is to add another class method with a different name (e.g., `ds$read2()`, or any name we choose). This alternate method signature would not have `out_xsize` and `out_ysize` arguments. Internally it would call `ds$read()`, passing `out_xsize = xsize` and `out_ysize = ysize`. This would be roughly analogous to something like `paste()` / `paste0()`.

Let me know if you think this would be a worthwhile addition, given the it is clunkier than just having default  values.

**Comment by kadyb** [comment]
Thanks for the explanation! I didn't know that and I thought such change would be rather simple. I think we can close this issue, because adding second function will only couse confusion, not make it simpler as default arguments (in my opinion).
