### ISSUE TITLE
create multiple bands with calc

### ISSUE THREAD

**Issue by wiesehahn** [USDAForestService/gdalraster#319]
I guess this is more a question than an issue, but there is no discussions enabled so I try here.

I would like to convert elevation data from single-band raster files (Float32) to [RGB-encoded](https://gis.stackexchange.com/questions/245562/how-to-transform-a-geotiff-dem-to-png-tiles-encoding-elevation-as-rgb-colors) raster files with 3 bands (BYTE). 

The reason behind this is that data in this format is used by web mapping libraries to minimize traffic as data can be better compressed.

The formula would be something like 
```r
to_terrainrgb <- function(dtm)
{
  startingvalue <- 10000
  precision <- 0.1
  rfactor <- 256*256 * precision
  gfactor <- 256 * precision
  
  r <- floor((startingvalue +dtm)*(1/precision) / 256 / 256)
  g <- floor((startingvalue +dtm - r*rfactor)*(1/precision) / 256) 
  b <- floor((startingvalue +dtm - r*rfactor - g*gfactor)*(1/precision))
  
  terrainrgb <- c(r,g,b)
  
  return(terrainrgb)
  rm("r","g", "b", "terrainrgb")
}
```

With `calc()` we can calculate some formula to get a single value based on multiple existing bands (e.g. NDVI). But is it possible to get (and write) multiple bands based on a single band? It would for sure be possible in multiple seperate calc operations to create R,G and B band seperately and write/update them to a file, but is it possible in a single go (I am not yet sure it it would even make sense perfomance wise)?

**Comment by ctoney** [comment]
I enabled discussions now so feel free to use them anytime. We can convert an issue if it seems like a better format in some cases.

`calc()` currently does not support multiband output but it would not be difficult to add. In your example, if the input `var.names = "ELEV"`, would you expect the calc expression to be `expr = "to_terrainrgb(ELEV)"`?

In that case, if we had an input vector of say 5 pixels for a simple example (i.e., a chunk of input data, in `calc()` this is a row of the input raster), it looks like:

```r
# a chunk of data read from the input raster:
ELEV <- c(1000, 2000, 3000, 3000, 2000) 

# the output data that `calc()` will write:
out <- to_terrainrgb(ELEV)

out
#> [1]   1   1   1   1   1 173 212 251 251 212 175 191 207 207 191

# as a matrix, each column is a vector of output for the 3 bands
dim(out) <- c(5, 3)
out
#>      [,1] [,2] [,3]
#> [1,]    1  173  175
#> [2,]    1  212  191
#> [3,]    1  251  207
#> [4,]    1  251  207
#> [5,]    1  212  191
```

In terms of specifying the return value of `expr`, it would be a matrix with `nrow()` equal to `length(ELEV)` and `ncol()` equal to the number of output bands, or the equivalent dimension-less vector. In matrix form, each column contains a vector of output values for a band.

There are other ways potentially that we could specify the data structure required for the return value of `expr`. Does it make sense to use the above? Do you have other thoughts on how it should work?

**Comment by ctoney** [comment]
#320 has been merged in main and the documentation updated at https://usdaforestservice.github.io/gdalraster/reference/calc.html. The dev version could be installed from GitHub, or from r-universe once 1.10.9100 has been built.

The data structure I was asking about is only for specifying what the return value of `expr` must be. It is for the documented spec now given in Details.

The code below is used in the unit test. The test currently only checks that `calc()` runs without error and returns the output filename. I'm not positive the output is correct since I'm not sure what it should look like. Once we have correct output, I'll add checksums for the output bands.

You can define the function before and then reference it in the expression as done below. Note that there could be an issue if you are defining that function locally inside another function, and also calling `calc()` there. That was case with `testthat` at least. In that case a workaround is to include the user-defined function within `expr` as done for the test at https://github.com/USDAForestService/gdalraster/blob/main/tests/testthat/test-gdalraster_proc.R#L64.

The example code below holds the raster in memory only because it writes to `/vsimem/`. Large raster should be fine if writing to disk. `calc()` is intended as a flexible but general purpose raster calculator. It is not in particular optimized for large data processing, but should work fine in many cases. Mainly it lacks an internal parallel option but that might be added in the future.

<details>
  <summary>Code</summary>

```r
library(gdalraster)

to_terrainrgb <- function(dtm) {
    startingvalue <- 10000
    precision <- 0.1
    rfactor <- 256*256 * precision
    gfactor <- 256 * precision

    r <- floor((startingvalue +dtm)*(1/precision) / 256 / 256)
    g <- floor((startingvalue +dtm - r*rfactor)*(1/precision) / 256)
    b <- floor((startingvalue +dtm - r*rfactor - g*gfactor)*(1/precision))

    return(c(r,g,b))
}

elev_file <- system.file("extdata/storml_elev.tif", package="gdalraster")
out_file <- "/vsimem/multiband-calc.tif"

result <- calc(expr = "to_terrainrgb(ELEV)",
               rasterfiles = elev_file,
               var.names = "ELEV",
               dstfile = out_file,
               dtName = "Byte",
               out_band = 1:3,
               nodata_value = 0)

(result == out_file)

ds <- new(GDALRaster, out_file)

plot_raster(ds, nbands = 3)

# compute stats and check info
ds$getStatistics(1, F, T)
ds$getStatistics(2, F, T)
ds$getStatistics(3, F, T)
ds$info()

ds$close()
deleteDataset(out_file)

# cf. the elev values
ds <- new(GDALRaster, elev_file)
plot_raster(ds, legend = TRUE)
ds$close()
```

</details>

**Comment by wiesehahn** [comment]
Nice, this looks good at first glance. 

We can decode the encoded data from the example above with
```r
from_terrainrgb <- function(R,G,B) {
  elevation <- -10000 + ((R * 256 * 256 + G * 256 + B) * 0.1)
  return(elevation)
}

out_file <- here("multiband-calc.tif")
revert_file <- here("multiband-calc-revert.tif")

result <- calc(expr = "from_terrainrgb(R,G,B)",
               rasterfiles = c(out_file, out_file, out_file),
               bands = c(1,2,3),
               var.names = c("R", "G", "B"),
               dstfile = revert_file,
               dtName = "Int16",
               out_band = 1,
               nodata_value = 0)

```
which should then get back our input data I think

**Comment by ctoney** [comment]
Thanks. I updated the test so that it now calculates the `revert_file` and compares it pixel-for-pixel back to the original elevation file (#321).

The only change to your `calc()` statement above was for nodata handling. When the RGB file is calculated in the test, nodata gets 0, so pixels in the original elevation raster that have a nodata value become 0, 0, 0 in the calculated RGB. But we do not set 0 as an intrinsic nodata value on the output RGB file. When it gets reverted, the 0, 0, 0 pixels revert to -10000. In the test, I assign -10000 as the `nodata_value` on `revert_file` and use `setRasterNodataValue = TRUE`. Then the `revert_file` is  equal to the original `elev_file` when compared per-pixel.

Of course, nodata could be handled differently if needed, but the above seems reasonable and should work fine for the test.

**Comment by ctoney** [comment]
Also, you asked above about using `write_mode = "update"` to write multiband output to an existing raster. That would be for updating (i.e., overwriting) the pixel data for existing bands, and should also work in the multiband case. In that case, the band numbers in `out_band` are not required to be sequential, and are not required to comprise all of the existing bands. For example, it could use something like `out_band = c(7, 5, 4)` if that matched the order of the output from `expr`.

Regarding the note

>(new bands cannot be created in dstfile)

In general, we cannot add new bands to an existing raster with GDAL. From the GDAL documentation for `GDALDataset::AddBand()`:

>This method will add a new band to the dataset if the underlying format supports this action. Most formats do not.

And then in the documentation for VRT:

>The `VRTDataset` class is one of the few dataset implementations that supports the `GDALDataset::AddBand()` method.

I don't believe adding bands in a VRT would be helpful though, for the case of writing output from `calc()`. So that is why the documentation for `calc()` notes that we cannot add new bands to an existing raster.

**Comment by wiesehahn** [comment]
Thanks for implementation!
