### ISSUE TITLE
recurse for vsi_read_dir

### ISSUE THREAD

**Issue by mdsumner** [USDAForestService/gdalraster#425]
I just tried a simple test, and it worked very well (18 objects at one level, 16000 objects one level up in an object store key-virtual-dir sense). 

Consider adding a `recurse` bool to 

https://github.com/USDAForestService/gdalraster/blob/af8af46a6f5728813a7f4a40b4230f0f5ab26344/src/gdal_vsi.cpp#L173

```C++
    if (recurse) {
       papszFiles = VSIReadDirRecursive(path_in.c_str());
    } else {
      papszFiles = VSIReadDirEx(path_in.c_str(), max_files);
    }
```

I mention it now as I was delighted it worked so well (and fast!), but there's always subtleties that I'm not thinking of. 

 I think `recurse` is the right name settled on by `fs` and other packages rather than `recursive` as in list.files(). 

This lets you delve from anywhere in the tree, my paths looked like

```R
## without recurse we need to know the lowest level
dsi <- "/vsis3/bucket/path/in/virtual/tree/202406"
dsi <- "/vsis3/bucket/path/in/virtual/tree"

## without recurse we will have to do it ourselves to discover the full tree
f <- vsi_read_dir(dsi, recurse  = TRUE)
```

There's a danger that there's no opt-out for a very large tree scan ...

Thanks!

**Comment by ctoney** [comment]
Thanks! `vsi_read_dir()` was missed when I added the `recursive` param to `vsi_mkdir()` and `vsi_rmdir()`.

I'm afraid we're stuck with `recursive` for the parameter name though, since that is the name already used in those other two functions.

Done in #426 and online docs updated at:
https://usdaforestservice.github.io/gdalraster/reference/vsi_read_dir.html
