### ISSUE TITLE
feature request: helper function to determine GDAL driver and data type from source 

### ISSUE THREAD

**Issue by brownag** [USDAForestService/gdalraster#552]
Thanks for this great package. I have been trialing using it for several different things and am particularly looking forward to the GDAL vector API implementation. 

I have been interested in replacing some existing functionality I have based on {vapour} and {terra} with tools in {gdalraster}. vapour has a handy helper function, [`vapour::vapour_driver()`](https://hypertidy.github.io/vapour/reference/GDAL-library.html), for determining the driver needed to read from a data source.

This type of helper function would help one to programmatically determine whether we need to use GDALRaster or GDALVector class to read data from an otherwise unknown source.

A hacky workaround I have currently attempts to create GDALRaster object, on failure attempts GDALVector, then extracts the driver short name from the result object. This works for simple cases, but it seems like gdalraster could have a simpler implementation similar to what vapour provides (i.e. https://github.com/hypertidy/vapour/blob/8fb170c6364a0363a9e2793d7b837b216f4e4d79/inst/include/gdallibrary/gdallibrary.h#L465-L478)

Beyond determining the driver required, it might be helpful to be able to determine whether the source contains vector, raster, or both. For example `"GPKG"` driver, and quite a few others, exists for both vector and raster sources so just knowing the driver name doesn't necessarily tell you which class(es) you need to instantiate from the source.

Thanks for your consideration!

**Comment by ctoney** [comment]
Thanks for the feedback. I'm hoping we'll have a release version with the vector API included before too much longer this winter.

#553 adds `identifyDriver()` with documentation online at https://usdaforestservice.github.io/gdalraster/reference/identifyDriver.html.

A helper function that describes what a source actually contains could return several pieces of information in a named list. The vector part is straightforward since we already have `ogr_ds_layer_count()` and `ogr_ds_layer_names()`. Raster is slightly more complicated since several formats support subdatasets, including GPKG. For example, if we instantiate a `GDALRaster` object on a GPKG file containing two raster tables, then we'll get a raster dataset but it will only contain a list of the subdatasets. The subdataset names can be obtained by querying the raster metadata in the SUBDATASETS domain. The names are the text strings that can be used to instantiate `GDALRaster` objects on the subdatasets. Checking for subdatasets and then parsing the metadata to get a character vector of just the names could be useful in a helper function.

Is that consistent with what you had in mind? We might have something like `inspectDataset()`, returning a list with named elements containing several pieces of information such as: the identified driver, supports_raster, contains_raster, contains_subdatasets, subdataset_names, supports_vector, contains_vector, layer_names.

**Comment by brownag** [comment]
Excellent, `identifyDriver()` is exactly what had in mind.

I realized there was some complexity with the latter request regarding source contents, but that is pretty much what I was hoping for. I think it would be very useful to have `inspectDataset()` as you describe!

**Comment by ctoney** [comment]
#559 was merged with documentation now online at https://usdaforestservice.github.io/gdalraster/reference/inspectDataset.html.

I'm happy to work on it more if you see anything we should change or add.

**Comment by brownag** [comment]
Thanks very much! I tested it a few different ways and at this time I think it covers all the needs raised in this issue! Much appreciated
